# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85c5a6eff451644e50e9777339a1f13081989d6f880a8dc19ac5ab425e442e1a9955c88ad9ec88dc434965d71833539b59df67d2d6734f0ffb74f749779d2cb0

test:
  secret_key_base: 6a2c899a0e64e108e4afc6ec473613cb8cf7e371c2581aa9813f7cf68349d17cb5da550705d963cdba570f4d1e768a95c624241cddbd43b18c6daa0e705a492d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
